#!/usr/bin/env python3
"""
下载 Fluent UI System Icons (微软官方图标库)
从 jsdelivr CDN 下载所有 regular (线性/描边) 图标

Fluent Icons 有多种尺寸: 16, 20, 24, 28, 32, 48
本脚本下载 24px 尺寸的 regular 图标
"""

import urllib.request
import urllib.error
import os
import json
import re

# Fluent Icons 图标名称列表（从官方仓库提取）
# 格式: 图标名称（不含前缀和后缀）
ICONS = [
    "accessibility", "access_time", "activity", "add", "add_circle", "add_square",
    "airplane", "airplane_take_off", "airplane_landing", "album", "alert", "alert_off",
    "alert_on", "alert_urgent", "align_center", "align_left", "align_right",
    "animal_cat", "animal_dog", "animal_rabbit", "animal_turtle", "app_folder",
    "app_recent", "app_store", "app_title", "apple", "apps", "apps_add_in",
    "apps_list", "archive", "archive_arrow_back", "archive_arrow_down",
    "archive_multiple", "arrow_autofit_content", "arrow_autofit_down",
    "arrow_autofit_height", "arrow_autofit_up", "arrow_autofit_width",
    "arrow_between", "arrow_bidirectional", "arrow_bounce", "arrow_clockwise",
    "arrow_counterclockwise", "arrow_curved", "arrow_down", "arrow_down_left",
    "arrow_down_right", "arrow_download", "arrow_download_off", "arrow_expand",
    "arrow_export", "arrow_export_ltr", "arrow_export_rtl", "arrow_fit",
    "arrow_fit_in", "arrow_flow", "arrow_forward", "arrow_hook_down_left",
    "arrow_hook_down_right", "arrow_hook_up_left", "arrow_hook_up_right",
    "arrow_import", "arrow_join", "arrow_key", "arrow_left", "arrow_maximize",
    "arrow_minimize", "arrow_minimize_vertical", "arrow_move", "arrow_next",
    "arrow_offset", "arrow_previous", "arrow_redo", "arrow_repeat_all",
    "arrow_repeat_all_off", "arrow_reset", "arrow_right", "arrow_rotate_clockwise",
    "arrow_rotate_counterclockwise", "arrow_routing", "arrow_shuffle", "arrow_sort",
    "arrow_sort_down", "arrow_sort_up", "arrow_split", "arrow_step_back",
    "arrow_step_in", "arrow_step_out", "arrow_step_over", "arrow_swap", "arrow_sync",
    "arrow_sync_circle", "arrow_sync_off", "arrow_undo", "arrow_up", "arrow_up_left",
    "arrow_up_right", "arrow_upload", "arrows_bidirectional", "assign", "asterisk",
    "asterisk_badge", "at", "attach", "attach_arrow_right", "attach_text",
    "auto_fit_height", "auto_fit_width", "autosum", "backspace", "backpack",
    "backward", "badge", "balloon", "bank", "bar_code", "bar_code_horizontal",
    "bar_code_vertical", "barrel", "basket", "battery", "battery_0", "battery_1",
    "battery_2", "battery_3", "battery_4", "battery_5", "battery_6", "battery_7",
    "battery_8", "battery_9", "battery_charge", "battery_checkmark", "battery_full",
    "battery_low", "battery_saver", "battery_warning", "beach", "beaker",
    "beaker_add", "beaker_dismiss", "beaker_edit", "beaker_empty", "beaker_off",
    "beaker_settings", "bed", "bedroom", "bicycle", "bin_full", "binary", "bind",
    "blinds", "block", "bluetooth", "bluetooth_connected", "bluetooth_disconnected",
    "bluetooth_searching", "blur", "board", "board_games", "board_split",
    "book", "book_add", "book_clock", "book_coins", "book_compass", "book_contacts",
    "book_database", "book_exclamation", "book_globe", "book_heartbeat",
    "book_info", "book_let", "book_letter", "book_money", "book_negative",
    "book_number", "book_open", "book_open_globe", "book_pulse", "book_question",
    "book_quantity", "book_search", "book_star", "book_template", "book_theta",
    "bookmark", "bookmark_add", "bookmark_multiple", "bookmark_off", "bookmark_search",
    "border", "border_all", "border_bottom", "border_bottom_double", "border_bottom_thick",
    "border_inside", "border_inside_horizontal", "border_inside_vertical",
    "border_left", "border_none", "border_outside", "border_right", "border_top",
    "border_tl", "border_tr", "bot", "bot_add", "bowl", "bowl_lettuce", "bowl_vegetables",
    "box", "box_arrow_left", "box_arrow_right", "box_checkmark", "box_dismiss",
    "box_edit", "box_multiple", "box_search", "box_toolbox", "braces", "braces_add",
    "braces_checkmark", "braces_dismiss", "braces_lettuce", "braces_variable",
    "brackets", "branch", "branch_fork", "branch_request", "breakout_room",
    "briefcase", "brightness_high", "brightness_low", "broad_activity_alert",
    "broadcast", "browse", "browse_live", "browser", "browser_tab", "browser_tabs",
    "bubble_hints", "bucket", "bug", "bug_arrow_counterclockwise", "building",
    "building_bank", "building_building", "building_checkmark", "building_desktop",
    "building_factory", "building_government", "building_home", "building_market",
    "building_middle", "building_mixed", "building_mobile", "building_multiple",
    "building_office", "building_people", "building_retail", "building_search",
    "building_shop", "building_swap", "building_tent", "button_menu", "calculator",
    "calendar", "calendar_add", "alendar_agenda", "calendar_arrow_counterclockwise",
    "calendar_arrow_right", "calendar_assistant", "calendar_cancel", "calendar_chat",
    "calendar_checkmark", "calendar_clock", "calendar_data_bar", "calendar_day",
    "calendar_delete", "calendar_descendant", "calendar_dismiss", "calendar_edit",
    "calendar_empty", "calendar_important", "calendar_later", "calendar_lettuce",
    "calendar_mail", "calendar_megaphone", "calendar_mirror", "calendar_month",
    "calendar_multiple", "calendar_note", "calendar_person", "calendar_phone",
    "calendar_play", "calendar_question_mark", "calendar_reply", "calendar_rtl",
    "calendar_search", "calendar_settings", "calendar_shield", "calendar_star",
    "calendar_sync", "calendar_temp", "calendar_today", "calendar_week_numbers",
    "calendar_week_start", "calendar_whisper", "call", "call_add", "call_checkmark",
    "call_connecting", "call_dismiss", "call_end", "call_exclamation", "call_forward",
    "call_inbound", "call_missed", "call_outbound", "call_park", "call_pause",
    "call_prohibited", "call_transfer", "call_video", "call_warning", "camera",
    "camera_add", "camera_edit", "camera_off", "camera_switch", "campground",
    "card_ui", "cards", "caret", "caret_down", "caret_left", "caret_right",
    "caret_up", "cart", "cast", "cast_multiple", "category", "cellular_3g",
    "cellular_4g", "cellular_5g", "cellular_data_1", "cellular_data_2",
    "cellular_data_3", "cellular_data_4", "cellular_off", "cellular_warning",
    "certificate", "channel", "channel_add", "channel_alert", "channel_arrow_left",
    "channel_dismiss", "channel_notification", "channel_share", "chat", "chat_add",
    "chat_bubbles_question", "chat_cursor", "chat_empty", "chat_help", "chat_multiple",
    "chat_off", "chat_settings", "chat_video", "chat_warning", "chat_wheel",
    "checkbox", "checkbox_arrow_right", "checkbox_checked", "checkbox_checked_sync",
    "checkbox_indeterminate", "checkbox_unchecked", "checkmark", "checkmark_circle",
    "checkmark_lock", "checkmark_note", "checkmark_square", "checkmark_underline_circle",
    "chevron", "chevron_circle", "chevron_down", "chevron_double_down",
    "chevron_double_left", "chevron_double_right", "chevron_double_up",
    "chevron_down_up", "chevron_left", "chevron_right", "chevron_up",
    "circle", "circle_ellipsis", "circle_half_fill", "circle_highlight",
    "circle_image", "circle_line", "circle_multiple", "circle_multiple_hint",
    "circle_multiple_hint_checkmark", "circle_off", "circle_shadow", "circle_small",
    "city", "class", "classification", "clear", "clear_formatting", "clipboard",
    "clipboard_arrow_right", "clipboard_bullet_list", "clipboard_bullet_list_ltr",
    "clipboard_bullet_list_rtl", "clipboard_checkmark", "clipboard_code", "clipboard_data_bar",
    "clipboard_heart", "clipboard_lettuce", "clipboard_link", "clipboard_more",
    "clipboard_multiple", "clipboard_paste", "clipboard_search", "clipboard_settings",
    "clipboard_text", "clipboard_text_edit", "clipboard_text_lettuce", "clock",
    "clock_add", "clock_alarm", "clock_arrow_counterclockwise", "clock_bill",
    "clock_checkmark", "clock_dismiss", "clock_lettuce", "clock_lock", "clock_pause",
    "clock_toolbox", "closed_caption", "cloud", "cloud_add", "cloud_archive",
    "cloud_arrow_down", "cloud_arrow_right", "cloud_arrow_up", "cloud_beaker",
    "cloud_checkmark", "cloud_cube", "cloud_database", "cloud_dismiss", "cloud_download",
    "cloud_edit", "cloud_error", "cloud_important", "cloud_link", "cloud_off",
    "cloud_search", "cloud_settings", "cloud_swap", "cloud_sync", "cloud_upload",
    "cloud_words", "clothes_hanger", "code", "code_block", "code_text", "code_text_edit",
    "code_text_square", "coin", "coin_multiple", "coin_stack", "collage",
    "collage_timeline", "collections", "collections_add", "color", "color_background",
    "color_fill", "color_gradient", "color_line", "color_palette", "column",
    "column_arrow_right", "column_double_compare", "column_edit", "column_insert",
    "column_left", "column_right", "column_single", "column_triple", "comma",
    "comment", "comment_add", "comment_arrow_left", "comment_arrow_right",
    "mention", "comment_checkmark", "comment_dismiss", "comment_edit", "comment_ellipsis",
    "comment_exclamation", "comment_lightning", "comment_link", "comment_mention",
    "comment_multiple", "comment_multiple_checkmark", "comment_multiple_link",
    "comment_note", "comment_off", "comment_quote", "comment_text", "communicator",
    "communicator_add", "communicator_location", "compass", "compass_ northwest",
    "component", "component_2_double_tap_swipe_down", "component_2_double_tap_swipe_up",
    "compose", "concat", "conference_room", "connected", "connector", "contact_card",
    "contact_card_group", "contact_card_link", "content_settings", "content_view",
    "content_view_gallery", "content_view_gallery_wide", "contrast", "controller",
    "controller_button", "convert", "convert_to_table", "convert_to_text",
    "cookies", "copy", "copy_add", "copy_select", "couch", "cube", "cube_add",
    "cube_arrow_curve", "cube_link", "cube_multiple", "cube_quick", "cube_rotate",
    "cube_sync", "cube_tree", "currency", "currency_dollar", "currency_dollar_euro",
    "currency_euro", "currency_euro_dollar", "cursor", "cursor_click", "cursor_hover",
    "cursor_prohibited", "cut", "dark_theme", "data", "data_area", "data_bar_horizontal",
    "data_bar_vertical", "data_bar_vertical_asc", "data_bar_vertical_desc",
    "data_histogram", "data_line", "data_pie", "data_sankey", "data_scatter",
    "data_sunburst", "data_treemap", "data_trending", "data_usage", "data_waterfall",
    "database", "database_arrow_down", "database_arrow_right", "database_arrow_up",
    "database_checkmark", "database_lettuce", "database_link", "database_multiple",
    "database_person", "database_plug_connected", "database_search", "database_warning",
    "database_window", "delete", "delete_arrow_back", "delete_dismiss", "delete_off",
    "denied", "density", "density_comfortable", "density_default", "density_compact",
    "design_ideas", "desk", "desktop", "desktop_arrow_right", "desktop_checkmark",
    "desktop_cursor", "desktop_edit", "desktop_flow", "desktop_keyboard",
    "desktop_mac", "desktop_off", "desktop_pulse", "desktop_signal", "desktop_toolbox",
    "device", "device_ear", "device_ear_lettuce", "device_eq", "device_meeting_room",
    "device_meeting_room_remote", "diagram", "dialpad", "dialpad_off", "diamond",
    "directions", "dining", "dining_table", "disability_cognitive", "document",
    "document_add", "document_arrow_down", "document_arrow_left", "document_arrow_right",
    "document_arrow_up", "document_briefcase", "document_bullet_list", "document_catch_up",
    "document_checkmark", "document_chevron_double", "document_clock", "document_copy",
    "document_css", "document_data", "document_dismiss", "document_edit",
    "document_endnote", "document_error", "document_ftp", "document_header",
    "document_header_arrow_down", "document_heartbeat", "document_image",
    "document_java", "document_justify", "document_lettuce", "document_landscape",
    "document_link", "document_list", "document_margins", "document_margin_bottom",
    "document_margin_left", "document_margin_right", "document_margin_top",
    "document_medicine", "document_multiple", "document_multiple_percent",
    "document_navigation", "document_one_page", "document_page", "document_page_bottom_center",
    "document_page_bottom_left", "document_page_bottom_right", "document_page_break",
    "document_page_number", "document_page_top_center", "document_page_top_left",
    "document_page_top_right", "document_pdf", "document_percent", "document_print",
    "document_prohibited", "document_question_mark", "document_queue", "document_queue_add",
    "document_queue_multiple", "document_ribbon", "document_search", "document_settings",
    "document_shortcut", "document_signed", "document_table", "document_table_arrow_right",
    "document_table_checkmark", "document_table_search", "document_table_truck",
    "document_text", "document_text_clock", "document_text_edit", "document_text_link",
    "document_text_toolbox", "document_toolbox", "document_width", "document_word",
    "document_yield", "dolphin", "door", "door_arrow_left", "door_arrow_right",
    "door_tag", "double_down", "double_swipe", "double_swipe_down", "double_swipe_up",
    "double_tap_swipe_down", "double_tap_swipe_up", "drafts", "drag", "draw_image",
    "draw_shape", "draw_text", "drawer", "drink", "drink_beverage", "drink_coffee",
    "drink_margarita", "drink_tea", "drink_to_go", "drive", "drive_bus", "drive_train",
    "drop", "dropdown", "dual_screen", "dual_screen_add", "dual_screen_arrow_right",
    "dual_screen_clock", "dual_screen_close", "dual_screen_dismiss", "dual_screen_error",
    "dual_screen_group", "dual_screen_header", "dual_screen_lock", "dual_screen_mirror",
    "dual_screen_pagination", "dual_screen_settings", "dual_screen_span",
    "dual_screen_tablet", "dual_screen_update", "dual_screen_vertical_scroll",
    "dual_screen_vibrate", "dumbbell", "dust", "dvd", "earth", "earth_filled",
    "earth_leaf", "edit", "edit_arrow_back", "edit_line_horizontal", "edit_lock",
    "edit_number", "edit_off", "edit_person", "edit_settings", "edit_style",
    "effects", "emoji", "emoji_add", "emoji_angel", "emoji_angry", "emoji_bonus",
    "emoji_cheek", "emoji_cry", "emoji_curious", "emoji_drool", "emoji_emotion",
    "emoji_faint", "emoji_flirt", "emoji_fun", "emoji_giggle", "emoji_grin",
    "emoji_hand", "emoji_heart", "emoji_hug", "emoji_laugh", "emoji_meh",
    "emoji_mind_blown", "emoji_mischief", "emoji_moon", "emoji_multiple",
    "emoji_nail_polish", "emoji_non_solid", "emoji_off", "emoji_puzzled",
    "emoji_relief", "emoji_rofl", "emoji_sad", "emoji_sad_slight", "emoji_smile",
    "emoji_smile_slight", "emoji_smirk", "emoji_sweat", "emoji_tired", "emoji_wink",
    "emoji_wink_slight", "emoji_wonder", "emoji_yawn", "engine", "engine_warning",
    "eraser", "eraser_medium", "eraser_small", "eraser_tool", "error_circle",
    "escalator", "escalator_down", "escalator_up", "expand_up_left", "expand_up_right",
    "extended_dock", "eye", "eye_lines", "eye_off", "eye_tracking", "eye_tracking_off",
    "eyedropper", "eyedropper_off", "fast_forward", "fast_forward_white", "fast_acceleration",
    "fast_motion", "fast_motion_white", "faucet", "faucet_droplet", "favorite",
    "fax", "feed", "feed_add", "feed_arrow_right", "feed_heart", "feed_lettuce",
    "feed_lightning", "feed_person", "feed_star", "ferry", "filter", "filter_add",
    "filter_arrow_right", "filter_dismiss", "filter_multiple", "filter_sync",
    "filter_3", "fingerprint", "fingerprint_badge", "fingerprint_lock", "fire",
    "fireplace", "fireworks", "flag", "flag_add", "flag_checkmark", "flag_clock",
    "flag_filled", "flag_off", "flag_pride", "flag_pride_intersex_inclusive_progress",
    "flag_pride_philadelphia", "flag_pride_progress", "flag_pride_ring", "flag_pride_ring_2",
    "flag_pride_triangle", "flag_pride_vertical", "flag_pride_wave",
    "flag_pride_waving", "flag_search", "flag_white", "flash", "flash_auto",
    "flash_checkmark", "flash_flow", "flash_light", "flash_off", "flash_settings",
    "flashlight", "flashlight_off", "flip_horizontal", "flip_vertical", "float",
    "flow", "flow_circle", "flowchart", "flowchart_circle", "fluent", "fluent_emoji_hint",
    "fluent_emoji_link", "fluid", "folder", "folder_add", "folder_arrow_left",
    "folder_arrow_right", "folder_arrow_up", "folder_briefcase", "folder_globe",
    "folder_heart", "folder_lettuce", "folder_lightning", "folder_link", "folder_list",
    "folder_multiple", "folder_open", "folder_open_down", "folder_open_lettuce",
    "folder_people", "folder_person", "folder_prohibited", "folder_public", "folder_search",
    "folder_settings", "folder_swap", "folder_sync", "folder_wheelchair", "folder_zip",
    "food", "food_apple", "food_cake", "food_carrot", "food_chicken_leg", "food_egg",
    "food_fish", "food_grains", "food_hamburger", "food_hot_dog", "food_lettuce",
    "food_pizza", "food_toast", "form", "form_multiple", "form_new", "form_sparkle",
    "fps_120", "fps_240", "fps_960", "frame", "frames", "freezing", "freezing_rain",
    "fridge", "frost", "full_screen", "full_screen_maximize", "full_screen_minimize",
    "funnel", "funnel_lettuce", "gallery", "game", "chat", "game_controller",
    "gauge", "gauge_add", "gavel", "gesture", "gift", "gift_card", "gift_open",
    "git", "git_branch", "git_compare", "git_fork", "git_pull", "git_pull_closed",
    "git_pull_request", "glasses", "glasses_off", "glitch", "globe", "globe_add",
    "globe_arrow_forward", "globe_arrow_left", "globe_arrow_right", "globe_clock",
    "globe_desktop", "globe_earth", "globe_edit", "globe_earth_lettuce",
    "globe_heart", "globe_important", "globe_lettuce", "globe_line_horizontal",
    "globe_ellipsis", "globe_link", "globe_heart", "globe_location", "globe_lock",
    "globe_more", "globe_off", "globe_person", "globe_search", "globe_shield",
    "globe_star", "globe_surface", "globe_sync", "globe_video", "grid", "grid_kanban",
    "grid_tiles", "grid_tiles_add", "gripper", "gripper_dots_vertical", "gripper_horizontal",
    "gripper_resize", "gripper_vertical", "guitar", "guitar_lettuce", "hammer",
    "hammer_screwdriver", "hammer_wrench", "hand_draw", "hand_point_left",
    "hand_point_right", "hand_wave", "handshake", "handshake_heart", "happy_heart",
    "hat_beanie", "hat_beanie_filled", "hat_graduation", "hat_graduation_add",
    "hat_graduation_lettuce", "hd", "hd_circle", "header", "header_1", "header_2",
    "header_3", "header_4", "headphones", "headphones_anc", "headphones_bluetooth",
    "headphones_lettuce", "headphones_sound_wave", "headset", "headset_add",
    "headset_vr", "health", "heart", "heart_broken", "heart_circle", "heart_half",
    "heart_heart", "heart_off", "heart_pulse", "heart_settings", "heartbeats",
    "hexagon", "hexagon_three", "hexagon_three_filled", "hexagon_three_filled_lettuce",
    "highlight", "highlight_accent", "highlight_lettuce", "history", "history_dismiss",
    "home", "home_add", "home_checkmark", "home_database", "home_more", "home_person",
    "home_search", "home_split", "home_storage", "hourglass", "hourglass_one_quarter",
    "hourglass_half", "hourglass_three_quarter", "hourglass_off", "icons", "idea",
    "image", "image_add", "image_alt_text", "image_arrow_back", "image_arrow_clockwise",
    "image_arrow_counterclockwise", "image_arrow_forward", "image_border",
    "image_circle", "image_component", "image_copy", "image_edit", "image_eraser",
    "image_library", "image_multiple", "image_multiple_off", "image_off",
    "image_polyhedron", "image_prohibited", "image_reflection", "image_search",
    "image_shadow", "image_sparkle", "image_split", "image_table", "image_zoom_in",
    "image_zoom_out", "inbox", "inbox_add", "inbox_arrow_right", "inbox_checkmark",
    "inbox_dismiss", "inbox_full", "inbox_lettuce", "inbox_multiple", "inbox_person",
    "inbox_search", "increment", "induction", "infinite", "infinite_grid", "inking_tool",
    "inking_tool_accent", "inking_tool_ellipse", "inking_tool_fill", "input",
    "insert", "inspect", "inspect_content", "installed", "ios_chevron", "ios_chevron_right",
    "ios_clear", "ios_person", "item", "item_multiple", "item_suggestion", "joystick",
    "key", "key_add", "key_command", "key_multiple", "key_reset", "keyboard",
    "keyboard_dock", "keyboard_layout_float", "keyboard_layout_one_handed_left",
    "keyboard_layout_one_handed_right", "keyboard_layout_resize",
    "keyboard_layout_split", "keyboard_lowercase", "keyboard_shift",
    "keyboard_shift_uppercase", "keyboard_tab", "keyboard_undock", "keyboard_uppercase",
    "keyboard_123", "kid", "kid_heart", "kiosk", "kitchen", "knowledge_article",
    "label", "label_heart", "lancer", "laptop", "laptop_chat", "laptop_desktop",
    "laptop_dismiss", "laptop_lettuce", "laptop_person", "laptop_settings",
    "laptop_shield", "laptop_video", "large", "lasso", "launcher", "layer",
    "layer_diagonal", "layer_diagonal_add", "layer_diagonal_person", "layer_multiple",
    "leaf", "leaf_three", "leaf_three_filled", "left", "letter", "library",
    "library_add", "light", "lightbulb", "lightbulb_checkmark", "lightbulb_circle",
    "lightbulb_dismiss", "lightbulb_filled", "lightbulb_lettuce", "lightbulb_person",
    "lightbulb_quantifier", "lightbulb_settings", "lightbulb_spotlight",
    "lightbulb_yellow", "lightning", "lightning_bolt", "lightning_bolt_circle",
    "line", "line_4", "line_5", "line_dashes", "line_flow", "line_horizontal",
    "line_horizontal_1", "line_horizontal_1_dashes", "line_horizontal_2",
    "line_horizontal_3", "line_horizontal_4", "line_horizontal_5", "line_horizontal_dashes",
    "line_style", "line_thickness", "line_weight", "linear", "link", "link_add",
    "link_cellular", "link_dismiss", "link_edit", "link_ellipse", "link_heart",
    "link_multiple", "link_person", "link_settings", "link_square", "link_toolbox",
    "linked", "linked_color", "list", "list_lettuce", "list_bar", "list_bar_tree",
    "list_bullet", "list_quare", "list_rtl", "lists", "live", "local_language",
    "location", "location_add", "location_arrow_left", "location_arrow_right",
    "location_arrow_up", "location_off", "location_rtl", "location_sharp", "lock",
    "ock_closed", "lock_multiple", "lock_open", "lock_person", "lock_search",
    "lock_settings", "lock_shield", "lock_swap", "lock_toolbox", "loupe", "loupe_zoom",
    "luggage", "mail", "mail_add", "mail_alert", "mail_all", "mail_arrow_clockwise",
    "mail_arrow_counterclockwise", "mail_arrow_double_back", "mail_arrow_forward",
    "mail_arrow_up", "mail_attach", "mail_checkmark", "mail_clock", "mail_copy",
    "mail_dismiss", "mail_edit", "mail_ellipsis", "mail_error", "mail_heart",
    "mail_inbox", "mail_inbox_add", "mail_inbox_all", "mail_inbox_arrow_right",
    "mail_inbox_checkmark", "mail_inbox_dismiss", "mail_lettuce", "mail_link",
    "mail_list", "mail_more", "mail_move", "mail_multiple", "mail_off", "mail_open",
    "mail_open_person", "mail_pause", "mail_person", "mail_prohibited", "mail_question",
    "mail_read", "mail_read_multiple", "mail_rewind", "mail_search", "mail_settings",
    "mail_shield", "mail_unread", "mail_urgent", "mail_warning", "mailbox",
    "mailbox_lettuce", "mailbox_read", "mailbox_unread", "map", "map_drive",
    "map_multiple", "marker", "match", "match_app_layout", "math_formula",
    "math_format_linear", "math_format_professional", "math_symbols", "maximize",
    "meet_now", "megaphone", "megaphone_loud", "megaphone_off", "megaphone_urgent",
    "mention", "mention_arrow_down", "mention_bracket", "mention_link", "mention_person",
    "merge", "merge_video", "meridian", "mic", "mic_add", "mic_off", "mic_options",
    "mic_prohibited", "mic_record", "mic_settings", "mic_sleep", "mic_sparkle",
    "microscope", "midi", "military_technology", "military_technology_award",
    "minimize", "minimize_vertical", "missed_call", "mobile", "mobile_add",
    "mobile_arrow_right", "mobile_chat", "mobile_checkmark", "mobile_dismiss",
    "mobile_ellipse", "mobile_lettuce", "mobile_optimized", "mobile_screen",
    "mobile_triangle", "modeling", "money", "money_heart", "money_off", "money_settings",
    "money_hand", "more", "more_circle", "more_horizontal", "more_vertical",
    "mountain", "mountain_location_bottom", "mountain_location_top", "mouse",
    "mouse_heart", "movie", "movie_add", "movie_edit", "movie_error", "movie_off",
    "movie_search", "multiple", "multiple_lettuce", "multiple_window", "music",
    "music_note", "music_note_1", "music_note_2", "music_note_off", "music_off",
    "navigation", "navigation_location", "navigation_play", "navigation_unread",
    "network", "network_adapter", "network_adapter_external", "network_adapter_off",
    "network_adapter_wifi", "network_adapters", "network_check", "network_off",
    "new", "news", "news_search", "next", "next_frame", "night", "no",
    "no_road", "noise", "noise_cancelation", "notation", "note", "note_add",
    "note_book", "note_important", "note_multiple", "note_pin", "note_edit",
    "note_placeholder", "note_ribbon", "note_section", "note_subtract", "note_text",
    "note_text_clock", "note_text_edit", "note_text_person", "notebook",
    "notebook_add", "notebook_ellipse", "notebook_lettuce", "notebook_question_mark",
    "notebook_section", "notebook_subsection", "notebook_sync", "notepad",
    "notepad_ellipsis", "notepad_lettuce", "notepad_person", "notepad_search",
    "number", "number_circle", "number_circle_1", "number_circle_2", "number_circle_3",
    "number_circle_4", "number_circle_5", "number_circle_6", "number_circle_7",
    "number_circle_8", "number_circle_9", "number_row", "number_symbol",
    "number_symbol_square", "ocr", "ocr_lettuce", "octagon", "office", "office_apps",
    "offline", "offset", "on", "one_drive", "one_drive_folder", "open", "open_folder",
    "open_in_browser", "options", "organization", "organization_horizontal",
    "organization_vertical", "orientation", "orientation_inverse", "out",
    "outlook", "outgoing", "outlook_lettece", "oval", "oval_and_filled",
    "padding", "padding_down", "padding_left", "padding_right", "padding_top",
    "page", "page_add", "page_arrow_right", "page_clock", "page_data", "page_edit",
    "page_end", "page_ellipsis", "page_fit", "page_header", "page_heart",
    "page_lettuce", "page_link", "page_person", "page_search", "page_settings",
    "page_toolbox", "paint", "paint_brush", "paint_brush_arrow_down",
    "paint_brush_eraser", "paint_brush_eraser_sparkle", "paint_bucket",
    "paint_palette", "pair", "panel", "panel_bottom", "panel_bottom_add",
    "panel_left", "panel_left_add", "panel_left_contract", "panel_left_expand",
    "panel_left_focus", "panel_left_text", "panel_left_text_add",
    "panel_left_text_dismiss", "panel_right", "panel_right_add",
    "panel_right_contract", "panel_right_expand", "panel_right_focus",
    "panel_right_text", "panel_right_text_add", "panel_right_text_dismiss",
    "panel_separate_window", "panel_settings", "panel_top", "panel_top_add",
    "panorama", "panorama_sphere", "panorama_sphere_off", "paper", "paper_add",
    "paper_clip", "paper_plane", "paper_plane_lettuce", "paper_plane_right",
    "paper_plane_search", "paragraph", "paragraph_dir", "password",
    "password_lettuce", "password_person", "paste", "pause", "pause_circle",
    "pause_off", "payment", "payment_wireless", "pen", "pen_dismiss",
    "pen_eraser", "pen_eraser_lettuce", "pen_lettuce", "pen_options",
    "pen_prohibited", "pen_settings", "pen_sparkle", "people", "people_add",
    "people_audience", "people_call", "people_chat", "people_close",
    "people_community", "people_community_add", "people_ellipsis",
    "people_heart", "people_list", "people_lock", "people_money",
    "people_multiple", "people_queue", "people_search", "people_settings",
    "people_swap", "people_sync", "people_team", "people_team_add",
    "people_team_delete", "people_team_toolbox", "people_toolbox",
    "people_voice", "person", "person_accounts", "person_add", "person_alert",
    "person_arrow_left", "person_arrow_right", "person_arrow_right_back",
    "person_arrow_up", "person_available", "person_boards", "person_call",
    "person_call_lettuce", "person_chat", "person_chat_bubble",
    "person_circle", "person_clock", "person_delete", "person_dismiss",
    "person_ellipse", "person_ellipse_info", "person_heart",
    "person_info", "person_lettuce", "person_lightbulb", "person_link",
    "person_lock", "person_mail", "person_money", "person_more",
    "person_multiple", "person_note", "person_pill", "person_prohibited",
    "person_question", "person_question_mark", "person_ribbon",
    "person_running", "person_search", "person_settings",
    "person_shield", "person_sound", "person_sound_source",
    "person_star", "person_star_off", "person_standing",
    "person_subtract", "person_support", "person_swap",
    "person_sync", "person_tag", "person_tentative",
    "person_voice", "person_walking", "person_warning",
    "pet", "phone", "phone_add", "phone_arrow_right",
    "phone_cellular_access", "phone_chat", "phone_desktop",
    "phone_eraser", "phone_key", "phone_laptop", "phone_link",
    "phone_lock", "phone_multiple", "phone_page_header",
    "person_page_header", "phone_pagination",
    "phone_screen", "phone_shake", "phone_tablet",
    "phone_to_pc", "phone_update", "phone_vertical_scroll",
    "phone_vibrate", "photo", "photo_filter", "photo_heart",
    "photo_fill", "photo_lettuce", "photo_multiple", "photo_off",
    "photo_sparkle", "picture", "picture_in_picture",
    "picture_in_picture_enter", "picture_in_picture_exit",
    "pie", "pie_single", "pill", "pill_lettuce", "pin", "pin_add",
    "pin_off", "pin_lettuce", "pinned", "pinned_filled",
    "pinned_off", "pistol", "pivot", "pizza", "play", "play_circle",
    "play_circle_hint", "play_lettuce", "play_many", "play_off",
    "play_previous", "plug", "plug_connected", "plug_disconnected",
    "plug_disconnected_checkmark", "plug_disconnected_lettuce",
    "point_scan", "pointer", "pointer_enlarge", "pointer_left",
    "pointer_right", "pointer_shrink", "polar", "polygon",
    "polygon_ellipsis", "position_backward", "position_forward",
    "position_to_back", "position_to_front", "power", "power_button",
    "power_lettuce", "power_sleep", "predictions", "premium",
    "premium_filled", "premium_lettuce", "premium_person",
    "presence", "presence_available", "presence_away",
    "presence_blocked", "presence_busy", "presence_dnd",
    "presence_offline", "presence_oof", "presence_tentative",
    "presence_unknown", "preview", "preview_letttuce", "print",
    "print_add", "print_multiple", "pro", "pro_briefcase",
    "pro_briefcase_filled", "pro_camera", "pro_camera_add",
    "pro_camera_filled", "pro_cube", "pro_cube_add",
    "pro_cube_filled", "pro_filled", "pro_lettuce",
    "pro_multiple", "pro_screen", "pro_screen_add",
    "pro_screen_filled", "processing", "processing_lettuce",
    "product", "prohibited", "prohibited_multiple",
    "prohibited_note", "projection_screen", "projection_screen_dismiss",
    "puzzle", "puzzle_cube", "puzzle_piece", "puzzle_piece_lettuce",
    "qr_code", "question", "question_circle", "question_person",
    "question_circle_filled", "quick", "quick_add", "quick_lettuce",
    "quiet_hours", "quotes", "quotes_lettuce", "radio",
    "radio_button", "radio_button_lettuce", "ram", "rating",
    "rating_half", "rating_mature", "rating_lettuce", "rating_mature_lettuce",
    "raw", "raw_source", "read", "read_aloud", "read_out_loud",
    "reading", "reading_list", "reading_list_add", "reading_mode",
    "reading_mode_mobile", "real", "real_estate", "rear", "reboot",
    "receipt", "receipt_add", "receipt_heart", "receipt_lettuce",
    "receipt_money", "receipt_qr_code", "receipt_search",
    "receipt_sparkle", "record", "record_fill", "record_lettuce",
    "record_one", "record_stop", "recycle", "recycle_lettuce",
    "redo", "reflection", "refresh", "refresh_circle", "regex",
    "regex_lettuce", "renew", "reorder", "reorder_dots_horizontal",
    "reorder_dots_vertical", "repair", "repeat", "repeat_all",
    "repeat_all_off", "repeat_off", "repeat_one", "replay",
    "resize", "resize_lettuce", "resize_image", "resize_table",
    "resize_video", "resize_lettuce_horizontal", "resize_lettuce_vertical",
    "respond", "restart", "restore", "retry", "rewind",
    "rewind_white", "ribbon", "ribbon_add", "ribbon_lettuce",
    "ribbon_off", "ribbon_star", "ribbon_star_filled", "right",
    "robot", "rocket", "rocket_lettuce", "roller", "roller_shades",
    "roller_shades_closed", "roller_skate", "roller_skating",
    "room", "room_add", "rooms", "rotate", "rotate_90_clockwise",
    "rotate_90_counter_clockwise", "rotate_left", "rotate_right",
    "router", "router_filled", "router_lettuce", "row", "row_add",
    "row_child", "row_edit", "row_double", "row_insert", "row_multiple",
    "row_settings", "row_triple", "ruler", "ruler_pen", "ruler_triangle",
    "run", "run_all", "save", "save_arrow_right", "save_as",
    "save_copy", "save_edit", "save_lettuce", "save_multiple",
    "save_sync", "scale", "scale_fill", "scale_lettuce", "scales",
    "scales_lettuce", "scan", "scan_add", "scan_eraser",
    "scan_lettuce", "scan_object", "scan_person", "scan_qr_code",
    "scan_table", "scan_text", "scan_text_lettuce", "scatter",
    "scatter_plot", "scatter_plot_lettuce", "scratchpad",
    "scratchpad_lettuce", "screenshot", "screenshot_tablet",
    "search", "search_add", "search_arrow_clockwise",
    "search_arrow_counterclockwise", "search_eraser",
    "search_info", "search_letter", "search_lettuce",
    "search_multiple", "search_off", "search_person",
    "search_settings", "search_shield", "search_square",
    "search_visual", "search_zoom_in", "search_zoom_out",
    "seat", "seat_add", "seat_car", "seat_lettuce", "section",
    "section_add", "section_arrow_right", "section_lettuce",
    "section_multiple", "section_star", "select_all",
    "select_all_off", "selection", "selection_add",
    "selection_ellipse", "selection_lettuce", "selection_off",
    "send", "send_beaker", "send_clock", "send_copy",
    "send_lettuce", "send_lettuce_filled", "send_person",
    "serial", "serial_port", "server", "server_add",
    "server_arrow_forward", "server_checkmark", "server_lettuce",
    "server_link", "server_multiple", "server_play",
    "server_search", "server_settings", "server_shield",
    "server_surface", "server_update", "service", "set",
    "set_top_stack", "settings", "settings_add",
    "settings_alert", "settings_app", "settings_chat",
    "settings_checkmark", "settings_component",
    "settings_cog_multiple", "settings_core",
    "settings_ettuce", "settings_lock", "settings_person",
    "settings_search", "settings_shield", "settings_sync",
    "settings_urgent", "shapes", "shapes_add", "shapes_lettuce",
    "shapes_rectangle", "shapes_rectangle_lettuce",
    "shapes_regular_polygon", "shapes_star", "shapes_star_lettuce",
    "shapes_subtract", "shapes_union", "shapes_untag", "share",
    "share_android", "share_close_trailing", "share_ettuce",
    "share_multiple", "share_screen", "share_screen_person",
    "share_screen_person_overlay", "share_screen_stop",
    "share_screen_ettuce", "shield", "shield_add",
    "shield_checkmark", "shield_dismiss", "shield_dismiss_shield",
    "shield_eraser", "shield_error", "shield_ettuce",
    "shield_globe", "shield_keyhole", "shield_person",
    "shield_person_add", "shield_prohibited", "shield_question",
    "shield_task", "shift", "shift_ellipsis", "shift_question",
    "shifts", "shifts_add", "shifts_30_minutes",
    "shifts_30_minutes_lettuce", "shifts_activity",
    "shifts_akk", "shifts_akk_lettuce", "shifts_availability",
    "shifts_availability_lettuce", "shifts_checkmark",
    "shifts_clock", "shifts_day", "shifts_ettuce",
    "shifts_open", "shifts_pending", "shifts_pending_lettuce",
    "shifts_question_mark", "shifts_team", "shifts_tender",
    "shifts_tender_lettuce", "ship", "shirt", "shoe", "shoe_lettuce",
    "shop", "shop_add", "shop_ettuce", "shop_multiple",
    "shop_open", "shopping", "shopping_bag", "shopping_bag_arrow_right",
    "shopping_bag_lettuce", "shopping_bag_percent",
    "shopping_bag_play", "shopping_cart", "shopping_cart_arrow_right",
    "shopping_cart_lettuce", "shortpick", "shortpick_lettuce",
    "shortcut", "shortcut_add", "shower", "shower_head",
    "sidebar", "sign", "signature", "signature_ettuce",
    "sign_out", "signal", "signal_1", "signal_2", "signal_3",
    "signal_4", "signal_5", "signal_cellular_1",
    "signal_cellular_2", "signal_cellular_3", "signal_cellular_4",
    "signal_cellular_5", "signal_off", "signal_wifi_1",
    "signal_wifi_2", "signal_wifi_3", "signal_wifi_4",
    "signal_wifi_ettuce", "signal_wifi_off", "signature_capture",
    "simplification", "simplification_lettuce", "simulate",
    "siren", "sitemap", "sitemap_lettuce", "size",
    "size_lettuce", "sketch", "ski", "skip", "skip_backward",
    "skip_backward_10", "skip_backward_15", "skip_backward_30",
    "skip_forward", "skip_forward_10", "skip_forward_15",
    "skip_forward_30", "skip_forward_tab", "skip_forward_white",
    "skip_start", "skip_start_white", "skip_tab",
    "skip_tab_white", "skull", "slash", "slash_forward",
    "slash_forward_lettuce", "slicing", "slide",
    "slide_add", "slide_eraser", "slide_grid", "slide_lettuce",
    "slide_link", "slide_microphone", "slide_multiple",
    "slide_multiple_lettuce", "slide_multiple_search",
    "slide_rough", "slide_search", "slide_settings",
    "slide_size", "slide_text", "slide_transition",
    "slider", "slider_add", "slider_horizontal",
    "slider_multiple", "slider_range", "slider_tick",
    "slider_tooltip", "slider_vertical", "slideshow",
    "slow", "slow_motion", "slow_motion_lettuce",
    "small", "smart", "smart_glass", "smart_glass_lettuce",
    "smart_glass_off", "smartphone", "smell", "smile",
    "smile_lettuce", "smoke", "smoke_detector", "snow",
    "snow_lettuce", "snowflake", "soap", "soccer",
    "sock", "sofa", "solar", "solar_lettuce", "sort",
    "sort_add", "sort_arrow_down", "sort_arrow_up",
    "sort_down", "sort_lettuce", "sort_multiple",
    "sort_up", "sound", "sound_lettuce", "sound_source",
    "sound_source_lettuce", "sound_wave", "sound_wave_circle",
    "sound_wave_lettuce", "source", "source_add",
    "source_ettuce", "space", "space_bar", "space_design",
    "space_keyboard", "spacebar", "spacer", "sparkle",
    "sparkle_lettuce", "sparkle_settings", "sparkle_circle",
    "sparkle_heart", "speaker", "speaker_0", "speaker_1",
    "speaker_2", "speaker_0_lettuce", "speaker_bluetooth",
    "speaker_edit", "speaker_ettuce", "speaker_off",
    "speaker_settings", "special_effect", "spinner",
    "spinner_imply", "splitscreen", "splitscreen_add",
    "splitscreen_vertical", "split_horizontal", "split_vertical",
    "spool", "sport", "sport_american_football",
    "sport_basketball", "sport_baseball", "sport_bowling",
    "sport_cricket", "sport_golf", "sport_gymnastics",
    "sport_hockey", "sport_lettuce", "sport_puck",
    "sport_quidditch", "sport_rugby", "sport_running",
    "sport_soccer", "sport_softball", "sport_swimming",
    "sport_table_tennis", "sport_tennis", "sport_volleyball",
    "spray", "spray_can", "spray_lettuce", "spreadsheet",
    "square", "square_eraser", "square_lettuce",
    "square_multiple", "square_shadow", "square_text",
    "square_text_arrow_repeat_all", "squares",
    "squares_nested", "stack", "stack_add", "stack_arrow_forward",
    "stack_ettuce", "stack_off", "stack_star", "stack_vertical",
    "stadium", "staff", "star", "star_add", "star_arrow_right",
    "star_add_lettuce", "star_bookmark", "star_checkmark",
    "star_ellipse", "star_ettuce", "star_emphasis",
    "star_filled", "star_half", "star_off", "star_one_quarter",
    "star_off_lettuce", "star_prohibited", "star_settings",
    "star_three_quarter", "starburst", "starburst_lettuce",
    "starburst_setting", "status", "status_add", "status_lettuce",
    "status_circle", "status_circle_checkmark",
    "status_circle_error", "status_circle_lettuce",
    "status_circle_question_mark", "status_circle_settings",
    "status_clock", "status_clock_lettuce", "status_off",
    "status_person", "status_person_lettuce", "steps", "stethoscope",
    "sticker", "sticker_add", "sticker_lettuce", "stock",
    "stock_ettuce", "stock_down", "stock_up", "stop",
    "stop_circle", "stop_lettuce", "storage", "storage_lettuce",
    "store", "store_microsoft", "stream", "stream_add",
    "stream_ettuce", "street", "stretch", "strikethrough",
    "strikethrough_character", "string", "string_lettuce",
    "style", "style_guide", "style_guide_lettuce", "sub",
    "subtitles", "subtitles_lettuce", "subtract", "subtract_circle",
    "subtract_circle_arrow_back", "subtract_circle_arrow_forward",
    "subtract_square", "subtract_square_multiple",
    "subway", "suitcase", "sun", "sun_add", "sun_clock",
    "sun_lettuce", "sun_moon", "sun_off", "sun_question_mark",
    "sunrise", "sunrise_lettuce", "sunset", "sunset_lettuce",
    "supervised_user_circle", "support", "support_lettuce",
    "surface", "surface_earth", "surface_hub",
    "surface_earth_lettuce", "swimming", "swimming_lettuce",
    "swipe", "swipe_down", "swipe_ettuce", "swipe_left",
    "swipe_right", "swipe_up", "switch", "switch_camera",
    "switch_user", "switch_lettuce", "switch_off", "switch_on",
    "symbols", "symbols_lettuce", "sync", "sync_circle",
    "sync_lettuce", "sync_off", "system", "system_filled",
    "tab", "tab_add", "tab_arrow_left", "tab_arrow_right",
    "tab_desktop", "tab_desktop_arrow_clockwise",
    "tab_desktop_arrow_counterclockwise", "tab_desktop_ettuce",
    "tab_desktop_multiple", "tab_desktop_new_page",
    "tab_desktop_ripple", "tab_group", "tab_in_private",
    "tab_in_private_account", "tab_lettuce", "tab_multiple",
    "tab_new", "tab_new_lettuce", "tab_prohibited",
    "tab_shield", "tab_shield_dismiss", "tab_sweep",
    "tab_close", "table", "table_add", "table_alias",
    "table_arrow_move", "table_arrow_up", "table_cake",
    "table_calculator", "table_cells", "table_cells_merge",
    "table_cells_split", "table_cells_lettuce", "table_checkmark",
    "table_column", "table_column_add", "table_column_resize",
    "table_column_lettuce", "table_column_resize_left",
    "table_column_resize_right", "table_cursor",
    "table_delete", "table_dismiss", "table_edit",
    "table_ettuce", "table_eraser", "table_freeze",
    "table_freeze_column", "table_freeze_column_lettuce",
    "table_freeze_row", "table_image", "table_insert",
    "table_lettuce", "table_link", "table_lock",
    "table_lock_lettuce", "table_move_below",
    "table_move_left", "table_move_right", "table_move_up",
    "table_multiple", "table_not_tracked",
    "table_offset", "table_offset_add",
    "table_offset_lettuce", "table_offset_less",
    "table_offset_more", "table_settings",
    "table_resize_column", "table_resize_row",
    "table_row", "table_row_add", "table_row_resize",
    "table_row_lettuce", "table_search", "table_settings",
    "table_stack", "table_stack_below", "table_split",
    "table_switch", "table_table", "tablet",
    "tablet_lettuce", "tablet_laptop", "tablet_no_underscores",
    "tablet_smartphone", "table_time", "tabs", "tag",
    "tag_add", "tag_circle", "tag_dismiss", "tag_lettuce",
    "tag_lettuce_multiple", "tag_lettuce_question_mark",
    "tag_lettuce_search", "tag_multiple", "tag_off",
    "tag_question", "tag_search", "tags", "tape",
    "tape_drive", "target", "target_add", "target_edit",
    "target_lettuce", "target_lettuce_edit", "task",
    "task_add", "task_list", "task_list_add",
    "task_list_lettuce", "task_list_ltr", "task_list_rtl",
    "task_list_square", "task_list_square_add",
    "task_list_square_lettuce", "task_list_square_settings",
    "task_lettuce", "task_round", "task_settings",
    "task_square", "task_square_lettuce", "tasks", "tasks_app",
    "team", "team_add", "team_delete", "team_lettuce",
    "team_toolbox", "teamgroup", "teamgroup_lettuce",
    "teamgroup_lettuce_add", "teamgroup_lettuce_person",
    "teeth", "telescope", "temperature", "temperature_lettuce",
    "tent", "tent_lettuce", "terminal", "test",
    "test_add", "test_call", "test_cube",
    "test_cube_lettuce", "test_dismiss", "test_lettuce",
    "text", "text_add", "text_add_space_after",
    "text_add_space_before", "text_add_t", "text_align_center",
    "text_align_distributed", "text_align_distributed_vertical",
    "text_align_justify", "text_align_left", "text_align_right",
    "text_around", "text_asterisk", "text_asterisk_lettuce",
    "text_asterisk_square", "text_baseline",
    "text_baseline_lettuce", "text_bold", "text_bullet_list",
    "text_bullet_list_add", "text_bullet_list_ltr",
    "text_bullet_list_lettuce", "text_bullet_list_off",
    "text_bullet_list_rtl", "text_bullet_list_square",
    "text_bullet_list_square_clock", "text_bullet_list_square_lettuce",
    "text_bullet_list_square_person", "text_bullet_list_square_search",
    "text_bullet_list_square_warning", "text_calligraphy",
    "text_caret", "text_caret_down", "text_caret_lettuce",
    "text_caret_up", "text_cell", "text_cell_lettuce",
    "text_change", "text_change_accept", "text_change_arrow_next",
    "text_change_previous", "text_change_lettuce", "text_change_settings",
    "text_clear_formatting", "text_collapse", "text_color",
    "text_color_lettuce", "text_column", "text_column_one",
    "text_column_one_narrow", "text_column_one_wide",
    "text_column_one_wide_lettuce", "text_column_three",
    "text_column_two", "text_column_two_lettuce",
    "text_continuous", "text_coordinates", "text_count",
    "text_description", "text_direction", "text_direction_horizontal_ltr",
    "text_direction_horizontal_rtl", "text_direction_rotate_270_left",
    "text_direction_rotate_270_right", "text_direction_rotate_90_left",
    "text_direction_rotate_90_right", "text_direction_vertical",
    "text_edit", "text_edit_style", "text_effects",
    "text_ellipsis", "text_ellipsis_lettuce", "text_expand",
    "text_field", "text_field_lettuce", "text_first_line",
    "text_font", "text_font_lettuce", "text_font_size",
    "text_font_size_lettuce", "text_footnote", "text_format",
    "text_format_lettuce", "text_grammar", "text_grammar_arrow_left",
    "text_grammar_checkmark", "text_grammar_dismiss",
    "text_grammar_lettuce", "text_grammar_options",
    "text_grammar_settings", "text_grammar_sparkle",
    "text_grammar_wand", "text_hanging", "text_header",
    "text_header_1", "text_header_1_lines",
    "text_header_1_lines_caret", "text_header_2",
    "text_header_2_lines", "text_header_2_lines_caret",
    "text_header_3", "text_header_3_lines",
    "text_header_3_lines_caret", "text_horizontal_tab",
    "text_indent_decrease", "text_indent_decrease_ltr",
    "text_indent_decrease_ltr_lettuce", "text_indent_decrease_rtl",
    "text_indent_decrease_rtl_lettuce", "text_indent_increase",
    "text_indent_increase_ltr", "text_indent_increase_ltr_lettuce",
    "text_indent_increase_rtl", "text_indent_increase_rtl_lettuce",
    "text_italic", "text_justify", "text_justify_low",
    "text_line_spacing", "text_lettuce", "text_lettuce_column",
    "text_list", "text_list_lettuce", "text_list_roman_lower",
    "text_list_roman_upper", "text_margin", "text_margin_bottom",
    "text_margin_left", "text_margin_right", "text_margin_top",
    "text_more", "text_more_lettuce", "text_number_format",
    "text_number_format_lettuce", "text_number_list_ltr",
    "text_number_list_rtl", "text_paragraph",
    "text_paragraph_lettuce", "text_period",
    "text_period_lettuce", "text_proofing",
    "text_proofing_tools", "text_position",
    "text_position_lettuce", "text_position_square",
    "text_quote", "text_sort", "text_sort_ascending",
    "text_sort_descending", "text_sort_lettuce",
    "text_sort_lettuce_ascending", "text_sort_lettuce_descending",
    "text_space_after", "text_space_before", "text_spacing",
    "text_strikethrough", "text_subscript", "text_superscript",
    "text_tab", "text_tab_more", "text_title", "text_underline",
    "text_whitespaces", "text_whitespaces_lettuce", "text_word",
    "text_word_count", "text_wrap", "text_wrap_lettuce",
    "text_wrap_off", "textbox", "textbox_lettuce",
    "textbox_align", "textbox_align_bottom",
    "textbox_align_bottom_left", "textbox_align_bottom_right",
    "textbox_align_center", "textbox_align_left",
    "textbox_align_middle", "textbox_align_middle_left",
    "textbox_align_middle_right", "textbox_align_right",
    "textbox_align_top", "textbox_align_top_left",
    "textbox_align_top_right", "textbox_settings",
    "textbox_vertical", "thinking", "thumb",
    "thumb_dislike", "thumb_dislike_lettuce", "thumb_like",
    "thumb_like_lettuce", "ticket", "ticket_diagonal",
    "ticket_diagonal_lettuce", "ticket_lettuce", "time",
    "time_and_weather", "time_picker", "time_picker_lettuce",
    "timeline", "timeline_lettuce", "timer", "timer_10",
    "timer_2", "timer_off", "title", "toggle",
    "toggle_left", "toggle_multiple", "toggle_multiple_lettuce",
    "toggle_right", "toolbar", "toolbar_add",
    "toolbar_arrow_down", "toolbar_arrow_up",
    "toolbar_more", "toolbox", "toolbox_add",
    "toolbox_edit", "toolbox_lettuce", "toolbox_multiple",
    "toolbox_whirlpool", "tools", "tools_not_tracked",
    "tools_not_tracked_lettuce", "tools_lettuce",
    "tooth", "top", "top_speed", "tornado", "tornado_lettuce",
    "touch", "touch_lettuce", "toy", "toy_lettuce", "train",
    "train_board", "train_bullet", "train_multiple",
    "train_lettuce", "train_subway", "train_subway_variant",
    "tram", "transfer", "transfer_within",
    "transform", "transform_accent", "transform_lettuce",
    "transition", "transition_effect", "transition_fade",
    "transition_overlap", "transition_push",
    "transition_wipe", "translate", "translate_lettuce",
    "translate_off", "trash", "trash_add", "trash_arrow_up",
    "trash_arrow_up_lettuce", "trash_checkmark",
    "trash_lettuce", "trash_multiple", "trash_off",
    "trash_sync", "tray", "tray_item_add", "tray_item_remove",
    "treasure_chest", "tree", "tree_lettuce", "tree_deciduous",
    "tree_evergreen", "tree_multiple", "triangle",
    "triangle_down", "triangle_left", "triangle_right",
    "triangle_up", "trophy", "truck", "truck_clock",
    "truck_lettuce", "truck_trail", "trunk",
    "tv", "tv_lettuce", "tv_urban", "umbrella",
    "umbrella_lettuce", "uninstall", "unknown",
    "unknown_lettuce", "unlock", "unread",
    "unread_badge", "up", "upload", "upload_cloud",
    "upload_lettuce", "urgent", "urgent_lettuce",
    "url", "user", "user_accounts", "user_clock",
    "user_multiple", "user_prohibited", "user_settings",
    "user_star", "user_sync", "vehicle", "vehicle_lettuce",
    "vehicle_bicycle", "vehicle_bus", "vehicle_cab",
    "vehicle_car", "vehicle_car_collision",
    "vehicle_car_profile", "vehicle_car_profile_lettuce",
    "vehicle_delivery_truck", "vehicle_delivery_truck_clock",
    "vehicle_delivery_truck_lettuce", "vehicle_lettuce",
    "vehicle_moped", "vehicle_moped_lettuce", "vehicle_motorcycle",
    "vehicle_roadmark", "vehicle_ship", "vehicle_ship_lettuce",
    "vehicle_subway", "vehicle_subway_clock",
    "vehicle_subway_lettuce", "vehicle_truck",
    "vehicle_truck_bag", "vehicle_truck_clock",
    "vehicle_truck_cube", "vehicle_truck_lettuce",
    "vehicle_truck_profile", "vehicle_truck_settings",
    "vehicle_truck_trailer", "vehicle_vehicles",
    "vehicle_vehicles_lettuce", "vehicle_wheel", "version",
    "vertical", "video", "video_add", "video_background_effect",
    "video_bluetooth", "video_call", "video_call_lettuce",
    "video_chat", "video_clip", "video_clip_multiple",
    "video_clip_off", "video_clip_wand", "video_close",
    "video_eraser", "video_360", "video_360_off",
    "video_lettuce", "video_image", "video_link",
    "video_multiple", "video_off", "video_off_lettuce",
    "video_optimize", "video_person", "video_person_call",
    "video_person_lettuce", "video_person_pulse",
    "video_person_star", "video_person_star_off",
    "video_play", "video_play_pause", "video_prohibited",
    "video_recording", "video_recording_lettuce",
    "video_security", "video_security_lettuce", "video_settings",
    "video_switch", "video_transitions", "video_usb",
    "view", "view_desktop", "view_desktop_mobile",
    "view_full", "view_lettuce", "view_multiple",
    "virtual", "virtual_network", "virtual_network_toolbar",
    "visibility", "visibility_off", "visitor",
    "visual_search", "visual_sparkle", "visual_studio",
    "visual_studio_lettuce", "visual_studio_for_windows",
    "visual_studio_for_windows_lettuce", "voicemail",
    "voicemail_arrow_back", "voicemail_arrow_forward",
    "voicemail_lettuce", "volcano", "volume", "volume_add",
    "volume_off", "volume_lettuce", "volume_settings",
    "volume_0", "volume_1", "volume_2", "volume_lettuce",
    "vote", "vote_lettuce", "vote_person", "vr", "vr_lettuce",
    "wallet", "wallet_credit_card", "wallet_lettuce", "wallpaper",
    "wand", "wand_lettuce", "warning", "warning_lettuce",
    "warning_lock", "warning_shield", "warning_shield_lettuce",
    "washing", "washing_machine", "watch", "watch_lettuce",
    "water", "water_add", "water_drop", "water_drop_lettuce",
    "water_lettuce", "water_large", "water_opacity",
    "water_small", "water_vertical", "weather", "weather_blowing_snow",
    "weather_blowing_snow_lettuce", "weather_broken_cloudy",
    "weather_broken_cloudy_lettuce", "weather_cloudy",
    "weather_cloudy_lettuce", "weather_drizzle",
    "weather_drizzle_lettuce", "weather_duststorm",
    "weather_duststorm_lettuce", "weather_earthquake",
    "weather_earthquake_lettuce", "weather_foggy",
    "weather_foggy_lettuce", "weather_lettuce",
    "weather_hail_day", "weather_hail_day_lettuce",
    "weather_hail_night", "weather_hail_night_lettuce",
    "weather_hazy", "weather_hazy_lettuce", "weather_ice",
    "weather_ice_lettuce", "weather_lettuce",
    "weather_moon", "weather_moon_lettuce",
    "weather_moon_off", "weather_moon_off_lettuce",
    "weather_moonrise", "weather_moonrise_lettuce",
    "weather_moonset", "weather_moonset_lettuce",
    "weather_partly_cloudy_day", "weather_partly_cloudy_day_lettuce",
    "weather_partly_cloudy_night", "weather_partly_cloudy_night_lettuce",
    "weather_rain", "weather_rain_lettuce",
    "weather_rain_showers_day", "weather_rain_showers_day_lettuce",
    "weather_rain_showers_night", "weather_rain_showers_night_lettuce",
    "weather_rain_snow", "weather_rain_snow_lettuce",
    "weather_snow", "weather_snow_lettuce",
    "weather_snow_shower_day", "weather_snow_shower_day_lettuce",
    "weather_snow_shower_night", "weather_snow_shower_night_lettuce",
    "weather_snowflake", "weather_snowflake_lettuce",
    "weather_squalls", "weather_squalls_lettuce",
    "weather_sunny", "weather_sunny_lettuce",
    "weather_sunny_high", "weather_sunny_high_lettuce",
    "weather_sunny_low", "weather_sunny_low_lettuce",
    "weather_thunderstorm", "weather_thunderstorm_lettuce",
    "weather_tornado", "weather_tornado_lettuce",
    "web", "web_search", "web_lettuce", "web_asset",
    "web_cam", "web_cam_lettuce", "webcam_off",
    "webcam_on", "website", "website_add", "website_lettuce",
    "website_pan_horizontal", "website_pan_vertical",
    "weight", "weight_lettuce", "wheel", "wheel_lettuce",
    "wheelchair", "wheelchair_accessibility", "wheelchair_lettuce",
    "whiff", "wifi", "wifi_add", "wifi_1", "wifi_2", "wifi_3",
    "wifi_4", "wifi_lettuce", "wifi_lock", "wifi_off",
    "wifi_protected", "wifi_settings", "wifi_warning",
    "wind", "wind_lettuce", "window", "window_add",
    "window_ad", "window_app", "window_arrow_up",
    "window_brush", "window_bullet_list", "window_call",
    "window_column", "window_console", "window_database",
    "window_dev_tools", "window_dev_tools_lettuce",
    "window_dismiss", "window_edit", "window_ettuce",
    "window_favicon", "window_fingerprint",
    "window_grid", "window_header_horizontal",
    "window_header_vertical", "window_inprivate",
    "window_inprivate_account", "window_inprivate_lettuce",
    "window_lettuce", "window_link", "window_location",
    "window_location_lettuce", "window_location_target",
    "window_location_target_lettuce", "window_location_add",
    "window_location_disable", "window_location_off",
    "window_multiple", "window_multiple_swap",
    "window_new", "window_new_lettuce", "window_off",
    "window_play", "window_play_lettuce", "window_settings",
    "window_shield", "window_terminal", "window_text",
    "window_wrench", "windows", "windows_lettuce",
    "windows_logo", "windows_logo_lettuce", "wrench",
    "wrench_lettuce", "wrench_settings", "x", "x_box",
    "x_box_controller", "x_ray", "x_ray_lettuce", "xray",
    "yellow", "yellow_lettuce", "yin_yang", "your", "your_lettuce",
    "youtube", "youtube_lettuce", "zero_width", "zero_width_lettuce",
    "zip", "zip_folder", "zoom", "zoom_ettuce", "zoom_fit",
    "zoom_in", "zoom_out"
]

# 尺寸列表
SIZES = [16, 20, 24, 28, 32, 48]

def download_icon(icon_name, size, base_dir):
    """下载单个图标"""
    url = f"https://cdn.jsdelivr.net/npm/@fluentui/svg-icons@1.1.319/icons_regular/ic_fluent_{icon_name}_{size}_regular.svg"
    output_dir = os.path.join(base_dir, f"fluenticons/{size}_regular")
    output_path = os.path.join(output_dir, f"{icon_name}.svg")
    
    os.makedirs(output_dir, exist_ok=True)
    
    try:
        urllib.request.urlretrieve(url, output_path)
        return True
    except urllib.error.HTTPError:
        return False
    except Exception as e:
        print(f"  错误: {icon_name} ({size}) - {e}")
        return False

def main():
    print("=" * 60)
    print("下载 Fluent UI System Icons (微软官方图标库)")
    print("=" * 60)
    print(f"图标总数: {len(ICONS)}")
    print(f"尺寸: {SIZES}")
    print()
    
    base_dir = "/Users/lijf/Documents/assignsticker-verge/icons"
    
    # 默认下载 24px 的 regular 图标
    target_size = 24
    
    print(f"下载 {target_size}px regular (线性) 图标...")
    success = 0
    failed = 0
    
    for i, icon in enumerate(ICONS, 1):
        if download_icon(icon, target_size, base_dir):
            success += 1
        else:
            failed += 1
        
        if i % 100 == 0:
            print(f"  进度: {i}/{len(ICONS)} ({success} 成功, {failed} 失败)")
    
    print()
    print("=" * 60)
    print("下载完成!")
    print(f"  - 成功: {success} 个图标")
    print(f"  - 失败: {failed} 个图标")
    print(f"  - 保存位置: {base_dir}/fluenticons/{target_size}_regular/")
    print("=" * 60)

if __name__ == "__main__":
    main()
